### ISSUE TITLE
Rename GitHub repository

### ISSUE THREAD

**Issue by rgaiacs** [chainsawriot/methodshub-weat#11]
@chainsawriot why is this repository named `methodshub-weat` instead of `methodshub-sweater` or `methodshub-sweater-tutorial`?

**Comment by chainsawriot** [comment]
b/c the method is really called WEAT (Word Embedding Association Test), although the tool is called `sweater`. It's like I would call a tutorial BERT classification, rather than a tutorial of Hugging Face.

But I am fine with the rename, if it makes the administration easier. Just let me know which one is better.

**Comment by rgaiacs** [comment]
@chainsawriot Thanks for the clarification. So we keep the GitHub repository name as is. And we change things on Methods Hub.

Do you prefer

![Screenshot 2024-12-13 at 11-50-56 Gallery - GESIS](https://github.com/user-attachments/assets/193dc4dd-d3e6-4634-9c40-f8b0acc1d1b3)

or

![Screenshot 2024-12-13 at 11-51-39 Gallery - GESIS](https://github.com/user-attachments/assets/9de46cd8-67e4-4139-8384-e250bdaa5699)

My preference is to keep the name `sweater` reserved for the Method entrance and use "Word Embedding Association Test" for the tutorial.

**Comment by chainsawriot** [comment]
The latter.
